name = "InternalFluidFlow"
uuid = "a3f4ffcb-63ab-449f-b58f-50e21d5ccbd2"
authors = ["Alexandre Umpierre <aumpierre@gmail.com>"]
version = "1.1.1"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Plots = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
